// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6sVi5dStkcUJ_oBTlIkvqX_ui0s7Qiw',
    appId: '1:536149132192:web:cffd7911b1fc0b3dec9ac5',
    messagingSenderId: '536149132192',
    projectId: 'loginwith-56d1d',
    authDomain: 'loginwith-56d1d.firebaseapp.com',
    storageBucket: 'loginwith-56d1d.firebasestorage.app',
    measurementId: 'G-SZ7ZN9YQRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGC6M2lPif1GKjK4g8wp3IJPL67YKFtKI',
    appId: '1:536149132192:android:93f2aa6f2871d8e1ec9ac5',
    messagingSenderId: '536149132192',
    projectId: 'loginwith-56d1d',
    storageBucket: 'loginwith-56d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4rCwZkvTCFwAlx7uQmCnnfwsPJc_oRy4',
    appId: '1:536149132192:ios:843ece25a9eb4403ec9ac5',
    messagingSenderId: '536149132192',
    projectId: 'loginwith-56d1d',
    storageBucket: 'loginwith-56d1d.firebasestorage.app',
    iosBundleId: 'com.example.loginWithGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4rCwZkvTCFwAlx7uQmCnnfwsPJc_oRy4',
    appId: '1:536149132192:ios:843ece25a9eb4403ec9ac5',
    messagingSenderId: '536149132192',
    projectId: 'loginwith-56d1d',
    storageBucket: 'loginwith-56d1d.firebasestorage.app',
    iosBundleId: 'com.example.loginWithGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG6sVi5dStkcUJ_oBTlIkvqX_ui0s7Qiw',
    appId: '1:536149132192:web:0c6748141e60fdf9ec9ac5',
    messagingSenderId: '536149132192',
    projectId: 'loginwith-56d1d',
    authDomain: 'loginwith-56d1d.firebaseapp.com',
    storageBucket: 'loginwith-56d1d.firebasestorage.app',
    measurementId: 'G-VX7Z0RHD03',
  );
}
